### ISSUE TITLE
Emails should be unique

### ISSUE THREAD

**Issue by noumxn** [noumxn/Task-Management-Application#19]
Need a helper function that makes sure the email being used by a user while registering is not already associated to an account.
- You can either create a new helper function called `checkEmailUnique(email)` or you can update the `checkEmail(email) function that already exists.
- In both cases make sure this function is `async` because you are performing DB operations.
- Throw `CONFLICT` error response.
- If you create a new function, call it in both `createUser()` and `updateUser()`.
- If you don't create a new function and choose to update the `checkEmail()`, make sure the `await` the existing function calls in both `createUser()` and `updateUser()`.

**Comment by Mikeyboy02** [comment]
I implemented a checkEmail function as a helper in Users. Also I fixed Update user since it would fail if given the original username
