### ISSUE TITLE
Need change in the updateTask() function in data/tasks.js

### ISSUE THREAD

**Issue by noumxn** [noumxn/Task-Management-Application#33]
- This change would be to account for tasks that are stored in checklists of different users. So I think you would first need to check if the task being updated has a new name. 
- Then implement a way to go through all the users that is in the `assignedTo` list of the board.
- Once you have all the assignedTo users, you see which of these users currently have the task that is being updated in their `checkList`. If a user has an item in their checkList that matches the `taskId` of the task being updated, you call the `updateCheckListItem()` function from data/checkList.js.
- Lmk if you have any questions regarding this.

**Comment by markfalletta** [comment]
Implemented in homepage_route
